// File generated by manual configuration for persistence.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// After you register a **Web** app in Firebase (same project as Android/iOS),
  /// paste its `appId` from the `firebaseConfig` snippet here, or pass
  /// `--dart-define=FIREBASE_WEB_APP_ID=1:804782276759:web:xxxx` when running
  /// `flutter run -d chrome`. You can also run:
  /// `flutterfire configure --project=catch-ride95 --platforms=android,ios,web`
  /// (requires the [Firebase CLI](https://firebase.google.com/docs/cli)).
  static const String _kCommittedWebAppId =
      '1:804782276759:web:6cd6c0d34285b66f5ae9d2';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      const envWebAppId = String.fromEnvironment(
        'FIREBASE_WEB_APP_ID',
        defaultValue: '',
      );
      final webAppId =
          _kCommittedWebAppId.isNotEmpty ? _kCommittedWebAppId : envWebAppId;
      if (webAppId.isEmpty) {
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for web.\n\n'
          '1. Open Firebase Console → Project "catch-ride95" → Project settings → '
          'Your apps → Add app → Web.\n'
          '2. Copy the Web `appId` from the config (format '
          '`1:804782276759:web:...`).\n'
          '3. Either paste it into `_kCommittedWebAppId` in lib/firebase_options.dart, '
          'or run:\n'
          '   flutter run -d chrome '
          '--dart-define=FIREBASE_WEB_APP_ID=<your-web-app-id>\n\n'
          'Or install Firebase CLI and run '
          '`flutterfire configure --platforms=android,ios,web`.',
        );
      }
      const webApiKey = String.fromEnvironment(
        'FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyCi1DoXvdJSa7Cv-Nj-4Jr0Vs3HBHXWYK0',
      );
      return FirebaseOptions(
        apiKey: webApiKey,
        appId: webAppId,
        messagingSenderId: '804782276759',
        projectId: 'catch-ride95',
        authDomain: 'catch-ride95.firebaseapp.com',
        storageBucket: 'catch-ride95.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1DoXvdJSa7Cv-Nj-4Jr0Vs3HBHXWYK0',
    appId: '1:804782276759:android:c3c90264b9b5a9dc5ae9d2',
    messagingSenderId: '804782276759',
    projectId: 'catch-ride95',
    storageBucket: 'catch-ride95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfeJR2w-yXWSeWoN2sO3zT73xYIOsaXY',
    appId: '1:804782276759:ios:e10afd809d2898eb5ae9d2',
    messagingSenderId: '804782276759',
    projectId: 'catch-ride95',
    storageBucket: 'catch-ride95.firebasestorage.app',
    iosBundleId: 'com.app.catchride',
  );
}
