// File generated by manual configuration for persistence.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by manual configuration or running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1DoXvdJSa7Cv-Nj-4Jr0Vs3HBHXWYK0',
    appId: '1:804782276759:android:c3c90264b9b5a9dc5ae9d2',
    messagingSenderId: '804782276759',
    projectId: 'catch-ride95',
    storageBucket: 'catch-ride95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfeJR2w-yXWSeWoN2sO3zT73xYIOsaXY',
    appId: '1:804782276759:ios:e10afd809d2898eb5ae9d2',
    messagingSenderId: '804782276759',
    projectId: 'catch-ride95',
    storageBucket: 'catch-ride95.firebasestorage.app',
    iosBundleId: 'com.app.catchride',
  );
}
